// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/events/v1/events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a single APM event (request, query, cache, exception)
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of event: request, query, cache, exception
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Timestamp in milliseconds since Unix epoch
	TimestampMs int64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Trace ID for distributed tracing correlation
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Span ID for this specific event
	SpanId string `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Parent span ID (optional, for nested spans)
	ParentId *string `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	// JSON blob containing event-specific attributes (max 32KB)
	AttributesJson string `protobuf:"bytes,6,opt,name=attributes_json,json=attributesJson,proto3" json:"attributes_json,omitempty"`
	// Key-value tags for filtering (max 20 tags)
	Tags          map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Event) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Event) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Event) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Event) GetAttributesJson() string {
	if x != nil {
		return x.AttributesJson
	}
	return ""
}

func (x *Event) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// IngestRequest contains a batch of events to ingest
type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events to ingest (max 500 per batch)
	Events        []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// IngestResponse contains the result of a batch ingestion
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the overall operation succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of events accepted
	Accepted int32 `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Number of events rejected
	Rejected int32 `protobuf:"varint,3,opt,name=rejected,proto3" json:"rejected,omitempty"`
	// Errors for rejected events
	Errors        []*EventError `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestResponse) GetErrors() []*EventError {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Ack acknowledges a single streamed event
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Span ID of the acknowledged event
	SpanId string `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Whether the event was accepted
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Error message if rejected
	Error         *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Ack) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// EventError describes an error for a specific event in a batch
type EventError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the event in the batch (0-based)
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Error code (e.g., "INVALID_TYPE", "PAYLOAD_TOO_LARGE")
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventError) Reset() {
	*x = EventError{}
	mi := &file_proto_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventError) ProtoMessage() {}

func (x *EventError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventError.ProtoReflect.Descriptor instead.
func (*EventError) Descriptor() ([]byte, []int) {
	return file_proto_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventError) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EventError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EventError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_events_v1_events_proto protoreflect.FileDescriptor

const file_proto_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/events/v1/events.proto\x12\x12velwatch.events.v1\"\xbd\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x12 \n" +
	"\tparent_id\x18\x05 \x01(\tH\x00R\bparentId\x88\x01\x01\x12'\n" +
	"\x0fattributes_json\x18\x06 \x01(\tR\x0eattributesJson\x127\n" +
	"\x04tags\x18\a \x03(\v2#.velwatch.events.v1.Event.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_parent_id\"B\n" +
	"\rIngestRequest\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.velwatch.events.v1.EventR\x06events\"\x9a\x01\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x03 \x01(\x05R\brejected\x126\n" +
	"\x06errors\x18\x04 \x03(\v2\x1e.velwatch.events.v1.EventErrorR\x06errors\"_\n" +
	"\x03Ack\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"P\n" +
	"\n" +
	"EventError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xa7\x01\n" +
	"\fEventService\x12O\n" +
	"\x06Ingest\x12!.velwatch.events.v1.IngestRequest\x1a\".velwatch.events.v1.IngestResponse\x12F\n" +
	"\fIngestStream\x12\x19.velwatch.events.v1.Event\x1a\x17.velwatch.events.v1.Ack(\x010\x01B>Z<github.com/velocitykode/velwatch-go/proto/events/v1;eventsv1b\x06proto3"

var (
	file_proto_events_v1_events_proto_rawDescOnce sync.Once
	file_proto_events_v1_events_proto_rawDescData []byte
)

func file_proto_events_v1_events_proto_rawDescGZIP() []byte {
	file_proto_events_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_v1_events_proto_rawDesc), len(file_proto_events_v1_events_proto_rawDesc)))
	})
	return file_proto_events_v1_events_proto_rawDescData
}

var file_proto_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_events_v1_events_proto_goTypes = []any{
	(*Event)(nil),          // 0: velwatch.events.v1.Event
	(*IngestRequest)(nil),  // 1: velwatch.events.v1.IngestRequest
	(*IngestResponse)(nil), // 2: velwatch.events.v1.IngestResponse
	(*Ack)(nil),            // 3: velwatch.events.v1.Ack
	(*EventError)(nil),     // 4: velwatch.events.v1.EventError
	nil,                    // 5: velwatch.events.v1.Event.TagsEntry
}
var file_proto_events_v1_events_proto_depIdxs = []int32{
	5, // 0: velwatch.events.v1.Event.tags:type_name -> velwatch.events.v1.Event.TagsEntry
	0, // 1: velwatch.events.v1.IngestRequest.events:type_name -> velwatch.events.v1.Event
	4, // 2: velwatch.events.v1.IngestResponse.errors:type_name -> velwatch.events.v1.EventError
	1, // 3: velwatch.events.v1.EventService.Ingest:input_type -> velwatch.events.v1.IngestRequest
	0, // 4: velwatch.events.v1.EventService.IngestStream:input_type -> velwatch.events.v1.Event
	2, // 5: velwatch.events.v1.EventService.Ingest:output_type -> velwatch.events.v1.IngestResponse
	3, // 6: velwatch.events.v1.EventService.IngestStream:output_type -> velwatch.events.v1.Ack
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_events_v1_events_proto_init() }
func file_proto_events_v1_events_proto_init() {
	if File_proto_events_v1_events_proto != nil {
		return
	}
	file_proto_events_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_events_v1_events_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_v1_events_proto_rawDesc), len(file_proto_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_events_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_events_v1_events_proto_depIdxs,
		MessageInfos:      file_proto_events_v1_events_proto_msgTypes,
	}.Build()
	File_proto_events_v1_events_proto = out.File
	file_proto_events_v1_events_proto_goTypes = nil
	file_proto_events_v1_events_proto_depIdxs = nil
}
